### ISSUE TITLE
Error while finding spec for 'PseudoNetCDF.pncdump' (<class 'ImportError'>: No module named 'PseudoNetCDF')

### ISSUE THREAD

**Issue by waldyd** [barronh/pseudonetcdf#13]
Hello,

I am having the following issue using PseudoNetCF on fedora 23:

```
[waldyd@master ~]$ python -m PseudoNetCDF.pncdump -f ffi1001 HOX_DC8_20040626_R0.ict
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib64/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib64/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/__init__.py", line 47, in <module>
    from .pncparse import PNC
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 413
    raise oute from e
                  ^
SyntaxError: invalid syntax
[waldyd@master ~]$ python -m PseudoNetCDF.pncdump -f ffi1001 HOX_DC8_20040626_R0.ict
python                    python2.7                 python3.4                 python3.4m                python3.4m-x86_64-config  
python2                   python3                   python3.4-config          python3.4m-config         python3-config            
[waldyd@master ~]$ python2 -m PseudoNetCDF.pncdump -f ffi1001 HOX_DC8_20040626_R0.ict
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib64/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib64/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/__init__.py", line 47, in <module>
    from .pncparse import PNC
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 413
    raise oute from e
                  ^
SyntaxError: invalid syntax
[waldyd@master ~]$ python -m PseudoNetCDF.pncdump -f ffi1001 HOX_DC8_20040626_R0.ict
python                    python2.7                 python3.4                 python3.4m                python3.4m-x86_64-config  
python2                   python3                   python3.4-config          python3.4m-config         python3-config            
[waldyd@master ~]$ python3 -m PseudoNetCDF.pncdump -f ffi1001 HOX_DC8_20040626_R0.ict
/usr/bin/python3: Error while finding spec for 'PseudoNetCDF.pncdump' (<class 'ImportError'>: No module named 'PseudoNetCDF')
```

Would you please give some ideas about how to solve this?

**Comment by barronh** [comment]
You are trying to use the Python3 version of PseudoNetCDF with Python2.7. Either update to Python3 or install the archived Python2 version of PseudoNetCDF.

**Comment by waldyd** [comment]
Hello,

Thanks for your help. I reinstalled PseudoNetCDF using pip and the problem is solved. But now, i am having the following issue dumping a UAM file:

```
[simeca@master ~]$ python -m PseudoNetCDF.pncdump -f uamiv simulaciones/camx/6.2/run/outputs/CAMx6.SIMECA.140726.avrg.grd01 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncdump.py", line 218, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncdump.py", line 213, in main
    ifiles, options = pncparse(has_ofile = False)
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 268, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 314, in pncprep
    fs = getfiles(ipaths, args)
  File "/usr/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 357, in getfiles
    raise IOError('Unable to open path with %s(path, **%s)\n\tpath="%s"\n\terror="%s"' % (file_format, str(format_options), ipath, str(e)))
IOError: Unable to open path with uamiv(path, **{})
        path="simulaciones/camx/6.2/run/outputs/CAMx6.SIMECA.140726.avrg.grd01"
        error="6.2600002"

```

Would you please give me nny ideas to solve this IOError?

Best Regards,

Néstor Waldyd

**Comment by barronh** [comment]
Sounds like the file may have an issue. Was CAMx compiled for big endian? If not, use the format help options to find the endian options. Then add the option, like -f "uamiv,endian='little'". That's a first guess. You can debug in an interactive environment. 





Barron Henderson
Asst. Professor, UF ESSIE EES
420 Black Hall; 352-846-2695

**Comment by waldyd** [comment]
Hello Professor Barron,

Thanks for your answer!


In our case, CAMx was compiled with the following options:

`FLGS = $(INCLUDES) -mcmodel=medium -O2 -pc 64 -Kieee -Mdalign -Mextend -Mnoframe -byteswapio -Bstatic_pgi
`

It worked with the following options:

`python -m PseudoNetCDF.pncdump -f **uamiv_new** 'simulaciones/camx/6.2/run/outputs/CAMx6.SIMECA.140726.avrg.grd01'`

Best Regards,

Néstor Waldyd

**Comment by barronh** [comment]
While I am glad it worked, uamiv_new is not a class that is often used. I still suspect the file is incomplete.
