### ISSUE TITLE
Using getproj() with numpy >= 2.0

### ISSUE THREAD

**Issue by colleenbaublitz** [barronh/pseudonetcdf#149]
Using the getproj() function, encountered the following error:

> 
> Traceback (most recent call last):
>   File "$PATH/Make_IASI_NH3.py", line 75, in <module>
>     proj = gf.getproj(withgrid=True)
>   File "/home/username/satellite/lib/python3.9/site-packages/PseudoNetCDF/core/_files.py", line 136, in getproj
>     return getproj(self, withgrid=withgrid)
>   File "/home/username/satellite/lib/python3.9/site-packages/PseudoNetCDF/coordutil.py", line 596, in getproj
>     return pyproj.Proj(proj4str, preserve_units=preserve_units)
>   File "/home/username/satellite/lib/python3.9/site-packages/pyproj/proj.py", line 109, in __init__
>     self.crs = CRS.from_user_input(projparams, **kwargs)
>   File "/home/username/satellite/lib/python3.9/site-packages/pyproj/crs/crs.py", line 501, in from_user_input
>     return cls(value, **kwargs)
>   File "/home/username/satellite/lib/python3.9/site-packages/pyproj/crs/crs.py", line 348, in __init__
>     self._local.crs = _CRS(self.srs)
>   File "pyproj/_crs.pyx", line 2378, in pyproj._crs._CRS.__init__
> pyproj.exceptions.CRSError: Invalid projection: +proj=lcc +lat_1=np.float64(33.0) +lat_2=np.float64(45.0) +lat_0=40.0 +lon_0=-97.0 +y_0=1728000.0 +x_0=2556000.0 +a=6370000.0 +b=6370000.0 +to_meter=12000.0 +no_defs +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): lcc: Invalid value for lat_1 and lat_2: |lat_1 + lat_2| should be > 0)
> 

**Barron's solution:**

_First, the quick fix:_

```
proj4str = '+proj=lcc +lat_0=40 +lon_0=-97 +lat_1=33 +lat_2=45 +x_0=2556000 +y_0=1728000 +R=6370000 +to_meter=12000 +no_defs'
cno = pycno.cno(proj4str)

```
OR

```
import cmaqsatproc as csp
gf = csp.open_griddesc('12US1')
cno = gf.csp.cno

```
_Second, the bigger issue:_

It looks like this is related to the new version of numpy released last month. The PseudoNetCDF code is using the builtin “repr” function to format the components of the projection. In all previous numpy versions, the repr of np.float64(33.) = '33.0'. (e.g., 1.26.4). In numpy v2, the repr has changed to np.float64(33.0). This breaks the construction of the string. So, right now, PseudoNetCDF is not compatible with numpy v2. 

**You can update your environment by running `python -m pip install 'numpy<2'`.** Then, it should work… There are several other packages we use that are not yet numpy 2.0 compliant, so it may be best to use a 1.x for now.

**Comment by barronh** [comment]
There is a set of fixes that passes all regression tests with numpy v2 and v1.26 in Python3.9 in branch [bugfix/proj-numpyv2](https://github.com/barronh/pseudonetcdf/tree/bugfix/proj-numpyv2).

This also addressed the deprecation of `tostring`, several other uses of `repr`, and several uses of recfromtxt.

**Comment by barronh** [comment]
Closed in bugfix version 3.4.1 (available pip install pseudonetcdf>=3.4.1).

ps, Planning to all automated actions to github. The current combination of TravisCI, GitHub workflows, and manual scripts have gotten confusing and have repo release and pypi out of sync.
