### ISSUE TITLE
Using pseudonetcdf..

### ISSUE THREAD

**Issue by Kiki029** [barronh/pseudonetcdf#16]
Hi,

I am new to Python and pseudonetcdf. I am trying to produce contour maps from CAMx output. But I can not complete the tutorial, as you can see at the end of the script I get this message: ImportError: No module named netCDF4

I have downloaded Python (x,y) and pseudonetcdf.

Any input would be helpful, thanks!!

Kiki

In [11]: runfile('C:/Users/userB/Desktop/NEW CAMX/camxexample.py', wdir='C:/Users/userB/Desktop/NEW CAMX')
Traceback (most recent call last):

  File "<ipython-input-11-937f4f9fdbe7>", line 1, in <module>
    runfile('C:/Users/userB/Desktop/NEW CAMX/camxexample.py', wdir='C:/Users/userB/Desktop/NEW CAMX')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/userB/Desktop/NEW CAMX/camxexample.py", line 9, in <module>
    from PseudoNetCDF.camxfiles.Memmaps import uamiv

  File "C:\Python27\lib\site-packages\PseudoNetCDF\__init__.py", line 29, in <module>
    from PseudoNetCDF import sci_var

  File "C:\Python27\lib\site-packages\PseudoNetCDF\sci_var.py", line 24, in <module>
    from .core._files import PseudoNetCDFFile, PseudoNetCDFFileMemmap, PseudoNetCDFVariables, OrderedDict

  File "C:\Python27\lib\site-packages\PseudoNetCDF\core\__init__.py", line 1, in <module>
    from ._files import *

  File "C:\Python27\lib\site-packages\PseudoNetCDF\core\_files.py", line 2, in <module>
    from PseudoNetCDF._getreader import registerreader

  File "C:\Python27\lib\site-packages\PseudoNetCDF\_getreader.py", line 5, in <module>
    from PseudoNetCDF.netcdf import NetCDFFile

  File "C:\Python27\lib\site-packages\PseudoNetCDF\netcdf.py", line 15, in <module>
    from netCDF4 import Dataset as NetCDFFile

ImportError: No module named netCDF4

**Comment by barronh** [comment]
You need to install netcdf4-python. See requirements. 

Barron

**Comment by Kiki029** [comment]
Barron thanks for the reply.

Now I am trying to install it on a server following 4. Linux without permissions. I get this reply:  
"Couldn't resolve host 'repo.continuum.io'"

This server has PGF

**Comment by barronh** [comment]
You'll save yourself a lot of trouble if you follow the Anaconda user install process. 

Barron Henderson, PhD
352-682-3579
barronh.com

**Comment by Kiki029** [comment]
Dear Baron,

Once again thank you your reply. Before I continue with this I would appreciate your advice on the following: I am planning to run CAMx for operational air quality forecasts on a server with iFort. So far we are performing weather forecasts (www.meteo.gr) and postprocessing/authomatic visualisation is done with NCL. Would I need NCL for maps and pseudonetcdf for contours? Could I do this only with NCL?

Thanks again
Vasiliki

**Comment by barronh** [comment]
Kiki - you can make maps and contours with PseudoNetCDF without NCL.
