### ISSUE TITLE
Trouble installing pseudonetcdf

### ISSUE THREAD

**Issue by danunes** [barronh/pseudonetcdf#18]
I am attempting to install PseudoNetCDF with Anaconda. I have not had much success. I would appreciate any assistance.  Also, I was attempting to install this for all users by using root. Is this a bad idea? It seems like anaconda is often installed by individuals. I am new to the Anaconda environment, so it is very possible I am doing something foolish.  

**With Python3 with or without sudo...**

(python2) [root@PrimaryNode1 ~]# source activate python3
(python3) [root@PrimaryNode1 ~]# sudo pip install https://github.com/barronh/pseudonetcdf/archive/master.zip
Collecting https://github.com/barronh/pseudonetcdf/archive/master.zip
  Downloading https://github.com/barronh/pseudonetcdf/archive/master.zip
     - 419kB 1.3MB/s
Requirement already satisfied: numpy>=1.2 in /usr/lib64/python2.7/site-packages (from PseudoNetCDF==3.0.1)
Requirement already satisfied: netCDF4 in /usr/lib64/python2.7/site-packages (from PseudoNetCDF==3.0.1)
Requirement already satisfied: pandas in /usr/lib64/python2.7/site-packages (from PseudoNetCDF==3.0.1)
Requirement already satisfied: scipy in /usr/lib64/python2.7/site-packages (from PseudoNetCDF==3.0.1)
Requirement already satisfied: matplotlib in /usr/lib64/python2.7/site-packages (from PseudoNetCDF==3.0.1)
Collecting yaml (from PseudoNetCDF==3.0.1)
  _Could not find a version that satisfies the requirement yaml (from PseudoNetCDF==3.0.1) (from versions: )
No matching distribution found for yaml (from PseudoNetCDF==3.0.1)_

**With Python 2 without sudo...**

(python2) [root@PrimaryNode1 scripts]# pip install https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip
Collecting https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip
  Downloading https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip (368kB)
    100% |████████████████████████████████| 378kB 980kB/s
    Complete output from command python setup.py egg_info:
    /tmp/pip-Y_VM_g-build/setup.py:19: UserWarning: libmfhdf.so.0: cannot open shared object file: No such file or directory
      warn(e.message)
    /tmp/pip-Y_VM_g-build/setup.py:19: UserWarning: No module named netCDF3
      warn(e.message)
    /tmp/pip-Y_VM_g-build/setup.py:19: UserWarning: No module named pupynere
      warn(e.message)
    /tmp/pip-Y_VM_g-build/setup.py:21: UserWarning: Did not find a 'true' NetCDFFile reader; 'true' NetCDF functionality will be disabled
      warn("Did not find a 'true' NetCDFFile reader; 'true' NetCDF functionality will be disabled")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Y_VM_g-build/setup.py", line 45, in <module>
        """ % (define_function, define_variable)
    NameError: name 'define_variable' is not defined
_Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Y_VM_g-build/_

**With Python 2 with sudo...**

(python2) [root@PrimaryNode1 ~]# sudo pip install https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip
Collecting https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip
  Downloading https://github.com/barronh/pseudonetcdf/archive/v2.0.1.zip (368kB)
    100% |████████████████████████████████| 378kB 899kB/s
Installing collected packages: PseudoNetCDF
  Running setup.py install for PseudoNetCDF ... done
Successfully installed PseudoNetCDF-2.0

But the package is not available.

**Comment by barronh** [comment]
Re separate email: Don't worry, I get notified about these.

First, stick with Python3 unless you have a specific python2 need.

Second, I think this is a bug with the dependencies. I recently enabled them and I guess that one was wrong (sorry)! I fixed it just now. Sorry. Can you try again and write back to confirm it works?

**Comment by danunes** [comment]
Installation was successful, but I get an error below on import. That said I tried a lot of crazy things to get this to install. Do you think I should blow out the installation and try again or do you see what I need to address next?

Thanks for your time.

>>> import PseudoNetCDF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/__init__.py", line 29, in <module>
    from PseudoNetCDF import sci_var
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/sci_var.py", line 30, in <module>
    from PseudoNetCDF.pncgen import Pseudo2NetCDF
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/pncgen.py", line 154, in <module>
    from PseudoNetCDF.camxfiles import Writers as CAMxWriters
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/camxfiles/__init__.py", line 38, in <module>
    from . import ipr
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/camxfiles/ipr/__init__.py", line 14, in <module>
    from . import Memmap
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/camxfiles/ipr/Memmap.py", line 30, in <module>
    from PseudoNetCDF.conventions.ioapi import add_cf_from_ioapi
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/__init__.py", line 1, in <module>
    from ._ioapi import add_cf_from_ioapi, get_ioapi_sphere, add_ioapi_from_ioapi, add_ioapi_from_cf
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py", line 13, in <module>
    warn('pyproj could not be found, so IO/API coordinates cannot be converted to lat/lon; to fix, install pyproj or basemap (e.g., `pip install pyproj)`')
  File "/opt/anaconda/envs/python3/lib/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
TypeError: clean_showwarning() takes from 4 to 5 positional arguments but 6 were given

**Comment by barronh** [comment]
I would recommend a clean install at this point. I'll also check on this. If it happens again after the clean install, install basemap.

**Comment by barronh** [comment]
The root of the problem is trying to allow for optional modules that trigger extra functionality without requiring users to have all libraries. This triggers a warning, which should have been no big deal.

In your case, the warnings module had been updated to use optional arguments that my system was not ready for. To make sure you don't have any other such issues, I recommend that you edit show the clean_showwarning function call signature.

In /opt/anaconda/envs/python3/lib/python3.6/site-packages/PseudoNetCDF/__init__.py

Change 
```
def clean_showwarning(message, category, filename, lineno, file=None):
```
to
```
def clean_showwarning(message, category, filename, lineno, file=None, line=None):
```

Note that you are just adding an unused line keyword. That will ensure that any other warnings that use the line keyword don't also trigger errors.  I'll add this as a bug fix.

**Comment by danunes** [comment]
Will do. Thanks again.
