### ISSUE TITLE
An issue of pncparse.py when a file is opened with a mode.

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#35]
Hi Barron,

In the #22 (Make CAMx inputs from new NWP), you explained that file can be opened with the following line,

outpncargs = PNC('--format=uamiv,r+', output_uamiv_path)

But this gives me an error message as follows,

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/people/jjung/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.py", line 555, in PNC
    ifiles, outargs = pncparse(args = args, ifiles = ifiles, parser = parser, **kwds)
  File "/usr/people/jjung/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.py", line 419, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/usr/people/jjung/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.py", line 595, in pncprep
    fs = getfiles(ipaths, args)
  File "/usr/people/jjung/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.py", line 642, in getfiles
    format_options = eval('dict(' + ', '.join(format_options) + ')')
  File "<string>", line 1
    dict(r+)

To resolve this issue, I changed the pncparse.py file. Following lines, 642-645, are the results of "diff old_file new_file"
         
```
642c642,645
<         format_options = eval('dict(' + ', '.join(format_options) + ')')
---
>         if format_options == [] :
>           format_options = eval('dict(' + ', '.join(format_options) + ')')
>         else:
>           format_options = eval('dict([("mode","' + ', '.join(format_options) + '")])')
```

Please review and confirm this if you think it is correct.

Thanks and happy new year

Jaegun

**Comment by barronh** [comment]
I think I made a mistake there. 

‘’’
outpncargs = PNC('--format=uamiv,mode=“r+“', output_uamiv_path)
‘’’

Please confirm that works for you. The quotes should be normal double quotes — don’t let them get formatted in the copy paste process.

**Comment by jaegunjung** [comment]
It works too. Thanks!

Jaegun
