### ISSUE TITLE
Issue to run pncglobal2cmaq.py

### ISSUE THREAD

**Issue by rpedruzzi** [barronh/pseudonetcdf#53]
Dear, 

I am trying to run the pncglobal2cmaq.py to generate BC for my CMAQ domains with the .bpch from GEOS-Chem v9.02 for the month of August 2010, but I'm facing the following problem when I try to run the code:

**PNC:/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py:134:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
Traceback (most recent call last):
  File "pncglobal2cmaq.py", line 1731, in <module>
    makeibcon(args)
  File "pncglobal2cmaq.py", line 1217, in makeibcon
    oldbcon = makedefaultbcon(metbdyprops, args)
  File "pncglobal2cmaq.py", line 813, in makedefaultbcon
    varkey_unit = [(varkey, getunit(varkey)) for varkey in varlist]
UnboundLocalError: local variable 'varlist' referenced before assignment

The command line that I'm using is:
~/anaconda3/bin/python3 pncglobal2cmaq.py  inputs/ts20100730.bpch --METBDY3D inputs/METBDY3D_d04_61x79 --METCRO3D inputs/METCRO3D_d04_61x79  --mapping=mappings.json  --tstep=10000 --outifolder=icon_61x79/ --outbfolder=bcon_61x79/ 

Can you help me figure out how to run it correctly?

Thank you so much for your help.
Regards
Rizzieri Pedruzzi

**Comment by barronh** [comment]
This is both something you can work around and something I'll update the code for.

# Explanation 

You're previous command likely used slightly different options. The script is designed to use profile.dat files to create a default profile for when a species mapping does not provide a better answer. The way you are running it assumes that the user will provide dummybcon.nc and dummyicon.nc. This isn't very clear in the help documentation (pncglobal2cmaq.py -h) and the error message you are receiving is no help either. I'll update the error message, but in the meantime below is a description of how to run it.

# Work Around

The --ICON and --BCON default to dummyicon.nc and dummybcon.nc, but they do not currently exist. Last time you ran it, either those existed or you supplied the options that help generate them.

The automatic generation of default icon/bcon files requires the --BCONPROFILEPATH and --ICONPROFILEPATH options. These should point to bc_profile_CB05.dat and ic_profile_CB05.dat that are available from CMAQ's github (or other profile files).

# Bug Fix

I can make it so that empty dummy files are created by default (a little scary) or so that a better error is generated. Thoughts?

**Comment by rpedruzzi** [comment]
Thank you for your reply Dr. Henderson

One question, if I set the --ICON and --BCON with the paths of --BCONPROFILEPATH and --ICONPROFILEPATH options, I will generate the default boundary conditions. Is it right?
Do I need to generate the default BC first for later the program populate it with concentrations from GEOS-Chem or I am using the wrong command line?

About your question about create a dummy files or do a better error message. I think it is better to improve the error message, because avoid confusion on which file is the correct.

**Comment by rpedruzzi** [comment]
Dear Prof. Henderson.

I was trying to figure it out how to run it and I found one issue with the mapping.file:

I'm using the following command to generate the mapping:
python3 pncglobal2cmaq.py inputs/ts20100730.bpch --gc-version 9 --template=cb05tucl_ae6_aq > mappings.json

and then the command to run it:
 python3 pncglobal2cmaq.py -f bpch inputs/ts20100730.bpch --gc-version 9 --METBDY3D inputs/METBDY3D_d04_61x79 --mapping=mappings.json  --tstep=10000 --outifolder=icon_61x79/ --outbfolder=bcon_61x79/

and I get this error:
Traceback (most recent call last):
  File "pncglobal2cmaq.py", line 1567, in <module>
    makeibcon(args)
  File "pncglobal2cmaq.py", line 1116, in makeibcon
    mappings_file = json.load(open(args.mapping, mode = 'r'))
  File "/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 9 (char 1379)

I looked at the mapping file and I notice that there a comma (',') at lines 14, 19 and 26. I deleted those commas and I type the command again, so I didn't get the problem with mapping file, but I still receiving the message :
**PNC:/nas/longleaf/home/pedruzzi/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py:159:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
Traceback (most recent call last):
  File "pncglobal2cmaq.py", line 1567, in <module>
    makeibcon(args)
  File "pncglobal2cmaq.py", line 1149, in makeibcon
    oldbcon = makedefaultbcon(metbdyprops, args)
  File "pncglobal2cmaq.py", line 766, in makedefaultbcon
    varkey_unit = [(varkey, getunit(varkey)) for varkey in varlist]
UnboundLocalError: local variable 'varlist' referenced before assignment


I looked at the GEOS-Chem web site (http://wiki.seas.harvard.edu/geos-chem/index.php/Linking_GEOS-Chem_to_CMAQ#pncglobal2cmaq) and I am following the steps, but still with no success.
 
Thank you for your help
Regards

**Comment by barronh** [comment]
Rizzieri

1) The default mapping is not likely appropriate. Do you have the version that we made as a part of that project?
2) use the BCONPROFILE or a single time backup BCON. The processor is using the backup BCON as a filler value, so it won't work if the size is complex. The BCONPROFILE is more similar to what was done for you previously.

**Comment by EdisonOrtiz** [comment]
Dear Prof. Henderson

At this moment I'm trying to run pncglobal2cmaq.py to generate BC an IC for CMAQ 5.0.2 installed for modelling Air Quality in Bogotá, and I have the following error:

pncglobal2cmaq.py ts20180427.bpch  --METBDY3D $bMETBDYf --METCRO3D $bMETCROf --mapping=mappings.json

Traceback (most recent call last):
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 896, in getfiles
    f = pncopen(ipath, **format_options)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/_getreader.py", line 91, in pncopen
    reader = getreader(*args, format=format, **kwds)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/_getreader.py", line 57, in getreader
    if checker(*args, **kwds):
TypeError: isMine() got an unexpected keyword argument 'nogroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/SIMCAB_DATA/transporte/anaconda3/bin/pncglobal2cmaq.py", line 1708, in <module>
    ifiles, args = pncparse(has_ofile=False, parser=parser)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 611, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 839, in pncprep
    fs = getfiles(ipaths, args)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 904, in getfiles
    raise oute  # from e
OSError: Unable to open path with bpch(path, **{'nogroup': True})
	path="ts20180427.bpch"
	error="isMine() got an unexpected keyword argument 'nogroup'"

All files pncglobal2cmaq.py needs exists, and I don't understand why path error is generated.

I would appreciate your response, if you need the files that I'm using, please let me know

**Comment by barronh** [comment]
What happens if you run

```
pncdump -f "bpch,nogroup=True" ts20180427.bpch
```

**Comment by EdisonOrtiz** [comment]
Thanks for your response Prof. Henderson

I tried to run "pncdump -f "bpch,nogroup=True" ts20180427.bpch" I got the following error:

[transporte@altair scripts]$ pncdump -f "bpch,nogroup=True" ts20180427.bpch
Traceback (most recent call last):
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 896, in getfiles
    f = pncopen(ipath, **format_options)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/_getreader.py", line 91, in pncopen
    reader = getreader(*args, format=format, **kwds)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/_getreader.py", line 57, in getreader
    if checker(*args, **kwds):
TypeError: isMine() got an unexpected keyword argument 'nogroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncdump.py", line 330, in <module>
    main()
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncdump.py", line 319, in main
    ifiles, options = pncparse(has_ofile=False)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 611, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 839, in pncprep
    fs = getfiles(ipaths, args)
  File "/SIMCAB_DATA/transporte/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/pncparse.py", line 904, in getfiles
    raise oute  # from e
OSError: Unable to open path with bpch(path, **{'nogroup': True})
        path="ts20180427.bpch"
        error="isMine() got an unexpected keyword argument 'nogroup'"

**Comment by barronh** [comment]
First, try again without nogroup.

```
pncload -f bpch ts20180427.bpch
```

If that works, update to the latest version of PseudoNetCDF. Do that by removing and reinstalling. 

It looks like it is trying other readers even though you've specified one. In that case, the isMine interface was trying to guess what the reader should be. I believe this issue has been fixed in v3.0.1.

Update to the latest stable version by uninstalling and reinstalling.

**Comment by EdisonOrtiz** [comment]
Thanks for your support Prof. Henderson

Updating Pseudonetcdf pncglobal2cmaq.py works perfectly

**Comment by barronh** [comment]
Sure
