### ISSUE TITLE
pncglobal2cmaq.py 

### ISSUE THREAD

**Issue by gc13141112** [barronh/pseudonetcdf#68]
"PRESS": {
            "expression": "(hyam[:].reshape(1, -1).T + hybm[:].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100.",
            "outunit": "Pa"
        },
I use PRESS= np.ones_like(O3[:,0][:, None])*1013.25  to replace the press, and I have an error when I process pncglobal2cmaq.py, as follows:

NO2, Traceback (most recent call last):
  File "/public/LIBRARY/python36/bin/pncglobal2cmaq.py", line 4, in <module>
    __import__('pkg_resources').run_script('PseudoNetCDF==3.0.1', 'pncglobal2cmaq.py')
  File "/public/LIBRARY/python36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/LIBRARY/python36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/public/LIBRARY/python36/lib/python3.6/site-packages/PseudoNetCDF-3.0.1-py3.6.egg/EGG-INFO/scripts/pncglobal2cmaq.py", line 1487, in <module>
    makeibcon(args)
  File "/public/LIBRARY/python36/lib/python3.6/site-packages/PseudoNetCDF-3.0.1-py3.6.egg/EGG-INFO/scripts/pncglobal2cmaq.py", line 1226, in makeibcon
    rpressv = eval(mappings_file['PRESS']['expression'], None, nd49.variables)
  File "<string>", line 1, in <module>
TypeError: 'float' object is not subscriptable

**Comment by barronh** [comment]
Instead of posting the code segment that you did not use, please post the segment from mappings.json (precisely) that you did use.

**Comment by gc13141112** [comment]
There are the original mappings.json(mappings.log) and the changed mappings.json (mappings_change.log). Since there is no such variable (PSURF), I added PSURF=np.ones_like(O3[:,0][:, None])*1013.25 in mappings_change.log,  as follows:
[mappings.log](https://github.com/barronh/pseudonetcdf/files/2830218/mappings.log)
[mappings_change.log](https://github.com/barronh/pseudonetcdf/files/2830219/mappings_change.log)

**Comment by gc13141112** [comment]
Thank you for your help! I can process pncglobal2cmaq.py.
