### ISSUE TITLE
psuedonetcdf does not import with matplotlib 3.1.1 installed

### ISSUE THREAD

**Issue by shoyer** [barronh/pseudonetcdf#69]
Example traceback:
```
Traceback (most recent call last):
  File "xarray/util/print_versions.py", line 146, in <module>
    import PseudoNetCDF
  File "/usr/share/miniconda/envs/test_env/lib/python3.6/site-packages/PseudoNetCDF/__init__.py", line 39, in <module>
    from . import cmaqfiles
  File "/usr/share/miniconda/envs/test_env/lib/python3.6/site-packages/PseudoNetCDF/cmaqfiles/__init__.py", line 21, in <module>
    from .profile import *
  File "/usr/share/miniconda/envs/test_env/lib/python3.6/site-packages/PseudoNetCDF/cmaqfiles/profile.py", line 5, in <module>
    from matplotlib.mlab import csv2rec
ImportError: cannot import name 'csv2rec'
```

csv2rec was removed from matplotlib in https://github.com/matplotlib/matplotlib/pull/12165

Due to this import error, psuedonetcdf integration in xarray is currently not getting tested.

**Comment by barronh** [comment]
Thanks for the catch! I am working to put out a fix.

**Comment by barronh** [comment]
@shoyer  - I've updated a   #bugfix/csv2rec

For integration with xarray, do I need to update the conda recipe or make a new recipe?

Thanks,

**Comment by shoyer** [comment]
Once you're uploaded the release to pypi, conda-forge should automatically
generate a pull request to update the conda recipe. You'll just have to
merge it.

**Comment by barronh** [comment]
@shoyer 

I think we're all set. How can I confirm?

https://github.com/conda-forge/pseudonetcdf-feedstock/pull/3

**Comment by shoyer** [comment]
Let's see the PNC tests get run with https://github.com/pydata/xarray/pull/3143

**Comment by shoyer** [comment]
Yes, it's working now!
