### ISSUE TITLE
PseudoNetCDF import error

### ISSUE THREAD

**Issue by barronh** [barronh/pseudonetcdf#70]
I'm having an issue with my PseudoNetCDF version when trying to do a import PseudoNetCDF as pnc, I get:

```
Traceback (most recent call last):
  File "cmaq_draw.py", line 7, in <module>
    import PseudoNetCDF as pnc
  File "C:\Users\jrwelsh\AppData\Local\Continuum\anaconda2\lib\site-packages\PseudoNetCDF\__init__.py", line 42, in <module>
    from PseudoNetCDF.core import PseudoNetCDFFile
  File "C:\Users\jrwelsh\AppData\Local\Continuum\anaconda2\lib\site-packages\PseudoNetCDF\core\__init__.py", line 10, in <module>
    from ._files import PseudoNetCDFFile, netcdf, PseudoNetCDFVariables
  File "C:\Users\jrwelsh\AppData\Local\Continuum\anaconda2\lib\site-packages\PseudoNetCDF\core\_files.py", line 723
    print('|' + '=' * nitems + '|', flush=True)
                                         ^
SyntaxError: invalid syntax
```

I know you mention editing the _init_.py file but I can't find the section to add to it.  If you can provide any help, that would be great!

Thanks!

Sincerely,
Jason Welsh

**Comment by barronh** [comment]
Jason,

It'd be great if you could submit this an an issue on github, so that I can track problems.

I have two initial thoughts here.
1) you are using python2.7, which would require "from __future__ import print_function" at the top to work with this package.
2) For you to encounter this code in _files.py, you are working with the master branch. Is that right? The best thing to do is install via conda, which would use the version 3.0.2. This is slightly older and doesn't include my latest edits... but that is why it is more stable. You may have to uninstall first and then run "conda install pseudonetcdf"

I know that we've answered the question here, but do you mind if I copy it to the issue tracker?

**Comment by barronh** [comment]
Hi Barron,

I appreciate your response to this and yes you can copy this to the issue tracker. 

Also, I did get it to work and it is installed now with the more stable version.  Doing a "conda install -c conda-forge pseudonetcdf" worked!

I appreciate you answering this question!  I'll make sure to remember this fix for the future!

Best,
Jason
